image: rocker/shiny-verse

stages:
- install
- build
- document
- check
- test
- deploy

include:
  - template: Code-Quality.gitlab-ci.yml

install_libs:
  stage: install
  script:
   - R -e 'install.packages(c("lintr", "styler", "testthat", "config", "RSelenium"))'
   # - r -e 'devtools::build(binary = TRUE)'
   - R -e 'lintr::checkstyle_output(lintr::lint_dir("."), "lintr_report.xml")'
  artifacts:
    reports:
      codequality: "lintr_report.xml"

unittests:
  stage: test
  script:
    - R -e 'install.packages(c("lintr", "styler", "testthat", "config", "RSelenium"))'
    - r -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'


code_quality:
  stage: test
  artifacts:
    paths: ["codeclimate_report.xml"]

# buildbinary:
#   stage: build
#   script:
#     - r -e 'devtools::build(binary = TRUE)'
# 
# linting:
#   stage: check
#   script:
#   - R -e 'lintr::lint_dir(".")'
