image: rocker/shiny-verse

stages:
- install
- build
- document
- check
- test
- deploy

install_libs:
  stage: install
  script:
   - R -e 'install.packages(c("lintr", "styler", "testthat", "config", "RSelenium"))'
   # - r -e 'devtools::build(binary = TRUE)'
   - R -e 'lintr::lint_dir(".")'

# buildbinary:
#   stage: build
#   script:
#     - r -e 'devtools::build(binary = TRUE)'
# 
# linting:
#   stage: check
#   script:
