image: rocker/shiny-verse

stages:
- build
- document
- check
- test
- deploy

buildbinary:
  stage: build
  script:
    - r -e 'devtools::build(binary = TRUE)'

# install_libs:
#   stage: build
#   script:
#    - R -e 'install.packages(c("lintr", "styler", "testthat"))'
# 
# test:
#   script:
#   - R -e 'install.packages(c("lintr", "styler", "testthat"))'

linting:
  stage: check
  script:
  - R -e 'lintr::lint_dir(".")'
