test_that("get_views_ui", {
  performance <- Performance$new()
  result <- performance$get_views_ui("Dummy")
  expect_equal(class(result)[1], "shiny.tag.list")
  expect_true(grepl("id=\"linkedin_views\"", result))
})
test_that("get_views_server", {
  performance <- Performance$new()
  shares <- data.table(id = c(1,2), views = c(10,20))
  result <- performance$get_views_server(NULL, shares)
  expect_equal(class(result)[1], "shiny.render.function")
  expect_equal(class(result()), "json")
  expect_true(grepl("\"title\":\"Views over time\"", result()))
})
test_that("get_likes_ui", {
  performance <- Performance$new()
  result <- performance$get_likes_ui("Dummy")
  expect_equal(class(result)[1], "shiny.tag.list")
  expect_true(grepl("id=\"linkedin_likes\"", result))
})
test_that("get_likes_server", {
  performance <- Performance$new()
  shares <- data.table(id = c(1,2), likes = c(10,20))
  result <- performance$get_likes_server(NULL, shares)
  expect_equal(class(result)[1], "shiny.render.function")
  expect_equal(class(result()), "json")
  expect_true(grepl("\"title\":\"Likes over time\"", result()))
})
test_that("get_comments_ui", {
  performance <- Performance$new()
  result <- performance$get_comments_ui("Dummy")
  expect_equal(class(result)[1], "shiny.tag.list")
  expect_true(grepl("id=\"linkedin_comments\"", result))
})
test_that("get_comments_server", {
  performance <- Performance$new()
  shares <- data.table(id = c(1,2), comments = c(10,20))
  result <- performance$get_comments_server(NULL, shares)
  expect_equal(class(result)[1], "shiny.render.function")
  expect_equal(class(result()), "json")
  expect_true(grepl("\"title\":\"Comments over time\"", result()))
})